name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: "-Dwarnings"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-build-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo test
      - run: cargo fmt --check
      - run: cargo clippy

  deploy:
    needs: build
    if: ${{github.event_name=='push' && github.ref=='refs/heads/main' && github.repository_owner=='sampsyo'}}
    runs-on: ubuntu-latest
    steps:
      - name: toolchain
        run: |
          sudo apt install -y musl-tools
          rustup target add x86_64-unknown-linux-musl
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-deploy-${{ hashFiles('**/Cargo.lock') }}
      - name: build
        run: cargo build --release --target=x86_64-unknown-linux-musl
      - name: deploy
        env:
          EXE: ./target/x86_64-unknown-linux-musl/release/al
          DEPLOY_HOST: al.radbox.org
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          ssh -i pk -o 'UserKnownHostsFile kh' $DEPLOY_USER@$DEPLOY_HOST 'mv al al.old || true'
          scp -i pk -o 'UserKnownHostsFile kh' $EXE $DEPLOY_USER@$DEPLOY_HOST:
          ssh -i pk -o 'UserKnownHostsFile kh' $DEPLOY_USER@$DEPLOY_HOST 'killall al || true'
