on:
  workflow_dispatch:

name: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: cargo build --release
      - name: Tailscale
        uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: deploy
        env:
          DEPLOY_HOST: scone
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          echo "$DEPLOY_KEY" > pk
          echo "$DEPLOY_KNOWN_HOSTS" > kh
          chmod 600 pk
          scp -i pk -o 'UserKnownHostsFile kh' ./target/release/al $DEPLOY_USER@$DEPLOY_HOST:
          ssh -i pk -o 'UserKnownHostsFile kh' $DEPLOY_USER@$DEPLOY_HOST 'killall al'
